// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmsavJ-Q4t2yx7O49iOQIq7LeMK35_iE',
    appId: '1:117956759164:web:4fbd60904bdc37f2b583f9',
    messagingSenderId: '117956759164',
    projectId: 'docya-paciente',
    authDomain: 'docya-paciente.firebaseapp.com',
    storageBucket: 'docya-paciente.firebasestorage.app',
    measurementId: 'G-WPC9GHSHV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5H4TK-GT-undXi4yumEafR7vVt1QzqE',
    appId: '1:117956759164:android:c2212224eff90c95b583f9',
    messagingSenderId: '117956759164',
    projectId: 'docya-paciente',
    storageBucket: 'docya-paciente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx04ixbSnAEtvgWE2iX0SOcQSpqiRyOq0',
    appId: '1:117956759164:ios:25a17a5407b2eba8b583f9',
    messagingSenderId: '117956759164',
    projectId: 'docya-paciente',
    storageBucket: 'docya-paciente.firebasestorage.app',
    iosBundleId: 'com.docya.paciente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx04ixbSnAEtvgWE2iX0SOcQSpqiRyOq0',
    appId: '1:117956759164:ios:d000a0ddf2f4adecb583f9',
    messagingSenderId: '117956759164',
    projectId: 'docya-paciente',
    storageBucket: 'docya-paciente.firebasestorage.app',
    iosBundleId: 'com.example.docyaPacienteandroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnmsavJ-Q4t2yx7O49iOQIq7LeMK35_iE',
    appId: '1:117956759164:web:c1d2dcae9ae8f9c9b583f9',
    messagingSenderId: '117956759164',
    projectId: 'docya-paciente',
    authDomain: 'docya-paciente.firebaseapp.com',
    storageBucket: 'docya-paciente.firebasestorage.app',
    measurementId: 'G-53E70K7M6Q',
  );

}